platform :ios, '9.0'

target 'Injoy' do
  use_frameworks!

pod 'SVProgressHUD'
pod 'Firebase'
pod 'Firebase/Auth'
#pod 'Firebase/Database'
pod 'RealmSwift'

end

#
#post_install do |installer|
#    installer.pods_project.targets.each do |target|
#        target.build_configurations.each do |config|
#            config.build_settings['CLANG_WARN_DOCUMENTATION_COMMENTS'] = 'NO'
#        end
#    end
#end
